name: Platformio
on: push

env:
  TARGET: nodemcuv2 # Must match the value after colon in platformio.ini (line 4: [env:nodemcuv2])
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Create environment file
      run: |
        echo "VERSION=${GITHUB_REF#$"refs/tags/v"}" > .env
        echo "MQTT_USER=${{ secrets.MQTT_USER }}" >> .env
        echo "MQTT_PASSWORD=${{ secrets.MQTT_PASSWORD }}" >> .env
        echo "MQTT_HOST=${{ secrets.MQTT_HOST }}" >> .env
        echo "MQTT_PORT=${{ secrets.MQTT_PORT }}" >> .env
        echo "WIFI_SSID_NAME=${{ secrets.WIFI_SSID_NAME }}" >> .env
        echo "WIFI_SSID_PASSWORD=${{ secrets.WIFI_SSID_PASSWORD }}" >> .env

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "data"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install PlatformIO
      run: pip install --upgrade platformio

    - name: Compile Firmware
      run: pio run -e ${{ env.TARGET }}
    - name: Upload Firmware
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: .pio/build/${{ env.TARGET }}/firmware.bin

    - name: Compile Filesystem
      if: steps.check_files.outputs.files_exists == 'true'
      run: pio run --target buildfs
    - name: Rename Filesystem file
      if: steps.check_files.outputs.files_exists == 'true'
      run: mv .pio/build/${{ env.TARGET }}/*fs.bin .pio/build/${{ env.TARGET }}/filesystem.bin
    - name: Upload Filesystem
      if: steps.check_files.outputs.files_exists == 'true'
      uses: actions/upload-artifact@v3
      with: 
        name: filesystem
        path: .pio/build/${{ env.TARGET }}/filesystem.bin

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download Firmware Files
      uses: actions/download-artifact@v3

    - name: Release Firmware
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./*/firmware.bin
        generateReleaseNotes: true
        allowUpdates: true

    - name: Release Filesystem
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./*/filesystem.bin
        generateReleaseNotes: true
        allowUpdates: true